database:
 host: localhost
 port: 3306
 name: image_process
 username: root
 password: root

spring.jpa.generate-ddl: true

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
  datasource:
    url: jdbc:mysql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: com.mysql.jdbc.Driver
    test-on-borrow: true
    validation-query: SELECT 1